CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    CREATE TABLE "JournalData" (
        "SavedSectors" jsonb,
        "SavedBrokers" jsonb
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    CREATE TABLE "Entries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "ComponentType" text NOT NULL,
        "CostRelevance" text,
        "PriceRelevance" text,
        "IsRelevantForOverview" boolean NOT NULL,
        "ContentWrapper_ContentValue" text NOT NULL,
        "ContentWrapper_ChangeNote" text,
        "TradeElementFK" integer NOT NULL,
        "CompositeFK" integer NOT NULL,
        CONSTRAINT "PK_Entries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    CREATE TABLE "Entries_History" (
        "DataElementFK" integer NOT NULL,
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ContentValue" text NOT NULL,
        "ChangeNote" text,
        CONSTRAINT "PK_Entries_History" PRIMARY KEY ("DataElementFK", "Id"),
        CONSTRAINT "FK_Entries_History_Entries_DataElementFK" FOREIGN KEY ("DataElementFK") REFERENCES "Entries" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    CREATE TABLE "TradeComposites" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Sectors" text[] NOT NULL,
        "SummaryId" integer NOT NULL,
        "Status" text NOT NULL,
        "OpenedAt" timestamp with time zone,
        "ClosedAt" timestamp with time zone,
        CONSTRAINT "PK_TradeComposites" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    CREATE TABLE "TradeElements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TradeActionType" text NOT NULL,
        "CompositeFK" integer NOT NULL,
        CONSTRAINT "PK_TradeElements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TradeElements_TradeComposites_CompositeFK" FOREIGN KEY ("CompositeFK") REFERENCES "TradeComposites" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    CREATE INDEX "IX_Entries_CompositeFK" ON "Entries" ("CompositeFK");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    CREATE INDEX "IX_Entries_TradeElementFK" ON "Entries" ("TradeElementFK");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    CREATE INDEX "IX_TradeComposites_SummaryId" ON "TradeComposites" ("SummaryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    CREATE INDEX "IX_TradeElements_CompositeFK" ON "TradeElements" ("CompositeFK");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    ALTER TABLE "Entries" ADD CONSTRAINT "FK_Entries_TradeComposites_CompositeFK" FOREIGN KEY ("CompositeFK") REFERENCES "TradeComposites" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    ALTER TABLE "Entries" ADD CONSTRAINT "FK_Entries_TradeElements_TradeElementFK" FOREIGN KEY ("TradeElementFK") REFERENCES "TradeElements" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    ALTER TABLE "TradeComposites" ADD CONSTRAINT "FK_TradeComposites_TradeElements_SummaryId" FOREIGN KEY ("SummaryId") REFERENCES "TradeElements" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250104174831_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250104174831_InitialCreate', '9.0.0');
    END IF;
END $EF$;
COMMIT;

