CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    CREATE TABLE "JournalData" (
        "SavedSectors" jsonb,
        "SavedBrokers" jsonb
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    CREATE TABLE "Entries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "ComponentType" integer NOT NULL,
        "CostRelevance" integer NOT NULL,
        "PriceRelevance" integer NOT NULL,
        "IsRelevantForOverview" boolean NOT NULL,
        "ContentWrapper_Content" text NOT NULL,
        "ContentWrapper_ChangeNote" text NOT NULL,
        "Content" text NOT NULL,
        "TradeElementFK" integer NOT NULL,
        "TradeCompositeFK" integer NOT NULL,
        CONSTRAINT "PK_Entries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    CREATE TABLE "Entries_History" (
        "CellRefId" integer NOT NULL,
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Content" text NOT NULL,
        "ChangeNote" text NOT NULL,
        CONSTRAINT "PK_Entries_History" PRIMARY KEY ("CellRefId", "Id"),
        CONSTRAINT "FK_Entries_History_Entries_CellRefId" FOREIGN KEY ("CellRefId") REFERENCES "Entries" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    CREATE TABLE "TradeComposites" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Sectors" text[] NOT NULL,
        "SummaryId" integer NOT NULL,
        CONSTRAINT "PK_TradeComposites" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    CREATE TABLE "TradeElements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TradeActionType" integer NOT NULL,
        "TradeCompositeFK" integer NOT NULL,
        CONSTRAINT "PK_TradeElements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TradeElements_TradeComposites_TradeCompositeFK" FOREIGN KEY ("TradeCompositeFK") REFERENCES "TradeComposites" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    CREATE INDEX "IX_Entries_TradeCompositeFK" ON "Entries" ("TradeCompositeFK");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    CREATE INDEX "IX_Entries_TradeElementFK" ON "Entries" ("TradeElementFK");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    CREATE INDEX "IX_TradeComposites_SummaryId" ON "TradeComposites" ("SummaryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    CREATE INDEX "IX_TradeElements_TradeCompositeFK" ON "TradeElements" ("TradeCompositeFK");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    ALTER TABLE "Entries" ADD CONSTRAINT "FK_Entries_TradeComposites_TradeCompositeFK" FOREIGN KEY ("TradeCompositeFK") REFERENCES "TradeComposites" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    ALTER TABLE "Entries" ADD CONSTRAINT "FK_Entries_TradeElements_TradeElementFK" FOREIGN KEY ("TradeElementFK") REFERENCES "TradeElements" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    ALTER TABLE "TradeComposites" ADD CONSTRAINT "FK_TradeComposites_TradeElements_SummaryId" FOREIGN KEY ("SummaryId") REFERENCES "TradeElements" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215155350_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241215155350_InitialCreate', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215165315_CreateAppRoles') THEN
    CREATE ROLE jta_app WITH LOGIN PASSWORD 'your_secure_password';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215165315_CreateAppRoles') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO jta_app;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215165315_CreateAppRoles') THEN
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO jta_app;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215165315_CreateAppRoles') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241215165315_CreateAppRoles', '9.0.0');
    END IF;
END $EF$;
COMMIT;

