services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"      # HTTP traffic
      - "443:443"    # HTTPS traffic
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/https-server.conf:/etc/nginx/conf.d/https-server.conf:ro
      - ./certbot-webroot:/var/www/certbot          # HTTP-01 challenge files
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx_logs:/var/log/nginx                   # Nginx logs
      - ./nginx/start-nginx.sh:/start-nginx.sh
    entrypoint: /bin/bash /start-nginx.sh

  web:
    image: ghcr.io/shaunday/horizons-retrospective/assetsflow-backend:latest
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - COMMIT_SHA=${COMMIT_SHA}
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
