services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Expose port 443 for HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount SSL certs
    depends_on:
      - web


  web:
    image: ghcr.io/shaunday/horizons-retrospective/assetsflow-backend:1.0.0  
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env # Load environment variables from .env file
