name: JS-TS Build & Test
description: Build, lint, and audit a JS/TS project

inputs:
  project-path:
    description: "Path to the project"
    required: true

runs:
  using: "composite"
  steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "22.17"

    - name: Install dependencies
      run: npm install
      working-directory: ${{ inputs.project-path }}

    - name: Set GIT_COMMIT
      run: echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      working-directory: ${{ inputs.project-path }}

    - name: Build project
      run: npm run build
      working-directory: ${{ inputs.project-path }}

    - name: Run lint
      run: npm run lint
      working-directory: ${{ inputs.project-path }}

    - name: Run audit
      run: npm run audit
      working-directory: ${{ inputs.project-path }}
