name: JS-TS Build & Test

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17'

      - name: Install dependencies
        working-directory: ${{ inputs.project-path }}
        run: npm install

      - name: Set GIT_COMMIT
        run: echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Run build
        working-directory: ${{ inputs.project-path }}
        run: npm run build

      - name: Run lint
        working-directory: ${{ inputs.project-path }}
        run: npm run lint

      - name: Run audit
        working-directory: ${{ inputs.project-path }}
        run: npm run audit
