name: 'Dotnet Build & Publish'
description: 'Builds .NET project and publishes Docker image with version.txt version check'

inputs:
  project-path:
    description: 'Path to the folder containing the .csproj file to publish'
    required: true
  image-name:
    description: 'Docker image name to build and push'
    required: true
  github-token:
    description: 'GitHub Token for registry login and API calls'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Fetch Git tags
      shell: bash
      run: git fetch --tags --force

    - name: Detect .csproj file in project folder
      id: detect_project
      shell: bash
      run: |
        PROJECT_FILE=$(ls "${{ inputs.project-path }}"/*.csproj 2>/dev/null | head -n1)
        if [ -z "$PROJECT_FILE" ]; then
          echo "❌ No .csproj file found in project path '${{ inputs.project-path }}'"
          exit 1
        fi
        echo "project-file=$PROJECT_FILE" >> $GITHUB_OUTPUT

    - name: Build .NET project
      uses: ./.github/actions/dotnet-build-test-common
      with:
        project-path: ${{ steps.detect_project.outputs.project-file }}

    - name: Publish .NET project
      shell: bash
      run: dotnet publish -c Release -r linux-x64 -o ./publish ${{ steps.detect_project.outputs.project-file }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract project version
      shell: bash
      run: |
        PROJECT_FILE="${{ steps.detect_project.outputs.project-file }}"

        VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" "$PROJECT_FILE" || true)

        if [ -z "$VERSION" ]; then
          echo "Error: Version not found"
          exit 1
        fi

        # Clean build metadata (+anything)
        CLEAN_VERSION=$(echo "$VERSION" | cut -d'+' -f1)

        echo "VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
        echo "Version: $CLEAN_VERSION"
        
    - name: Set build timestamp
      shell: bash
      run: echo "TIMESTAMP=$(TZ="Asia/Jerusalem" date --iso-8601=seconds)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.project-path }}/Dockerfile
        push: true
        build-args: |
          VERSION=${{ env.VERSION }}
          COMMIT_SHA=${{ github.sha }}
          BUILD_TIMESTAMP=${{ env.TIMESTAMP }}
        tags: |
          ghcr.io/shaunday/horizons-retrospective/${{ inputs.image-name }}:${{ env.VERSION }}
          ghcr.io/shaunday/horizons-retrospective/${{ inputs.image-name }}:latest
