name: zBuild & Test .NET (verbose)

on:
  push:
    branches:
      - main
    paths:
      - "./Server.AssetsFlow/**"
      - "./Server.PriceAlerts/**"  # Add additional paths as needed
  workflow_dispatch:  # Allow manual triggers

jobs:
  Restore-Build-Test:
    runs-on: ubuntu-latest  # The host runner
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0  # Docker container with .NET SDK 9

    strategy:
      matrix:
        server-path:  # Define all paths to test/build
          - ./Server.AssetsFlow
          - ./Server.PriceAlerts

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restore .NET dependencies
      run: dotnet restore
      working-directory: ${{ matrix.server-path }}

    - name: Build .NET project
      run: dotnet build --no-restore
      working-directory: ${{ matrix.server-path }}

    #- name: Run .NET tests
    #  run: dotnet test --no-build --verbosity normal
    #  working-directory: ${{ matrix.server-path }}
