// <auto-generated />
using System;
using DayJT.Journal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DayJTrading.Journal.Data.Migrations
{
    [DbContext(typeof(TradingJournalDataContext))]
    partial class TradingJournalDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DayJT.Journal.Data.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ComponentType")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContentWrapperId")
                        .HasColumnType("uuid");

                    b.Property<int>("CostRelevance")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<bool>("IsRelevantForOverview")
                        .HasColumnType("boolean");

                    b.Property<int>("PriceRelevance")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TradeComponentRefId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContentWrapperId");

                    b.HasIndex("TradeComponentRefId");

                    b.ToTable("TradeInputComponents");
                });

            modelBuilder.Entity("DayJT.Journal.Data.CellContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CellRefId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CellRefId");

                    b.ToTable("ContentModels");
                });

            modelBuilder.Entity("DayJT.Journal.Data.TradeComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("TradeActionType")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<Guid>("TradePositionCompositeRefId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradePositionCompositeRefId");

                    b.ToTable("TradeInputs");
                });

            modelBuilder.Entity("DayJT.Journal.Data.TradePositionComposite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("OverallTrades");
                });

            modelBuilder.Entity("DayJT.Journal.Data.Cell", b =>
                {
                    b.HasOne("DayJT.Journal.Data.CellContent", "ContentWrapper")
                        .WithMany()
                        .HasForeignKey("ContentWrapperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DayJT.Journal.Data.TradeComponent", "TradeComponentRef")
                        .WithMany("TradeActionInfoCells")
                        .HasForeignKey("TradeComponentRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentWrapper");

                    b.Navigation("TradeComponentRef");
                });

            modelBuilder.Entity("DayJT.Journal.Data.CellContent", b =>
                {
                    b.HasOne("DayJT.Journal.Data.Cell", "CellRef")
                        .WithMany("History")
                        .HasForeignKey("CellRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CellRef");
                });

            modelBuilder.Entity("DayJT.Journal.Data.TradeComponent", b =>
                {
                    b.HasOne("DayJT.Journal.Data.TradePositionComposite", "TradePositionCompositeRef")
                        .WithMany("TradeComponents")
                        .HasForeignKey("TradePositionCompositeRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradePositionCompositeRef");
                });

            modelBuilder.Entity("DayJT.Journal.Data.Cell", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("DayJT.Journal.Data.TradeComponent", b =>
                {
                    b.Navigation("TradeActionInfoCells");
                });

            modelBuilder.Entity("DayJT.Journal.Data.TradePositionComposite", b =>
                {
                    b.Navigation("TradeComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
