// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace JTA.Infrastructure.JTA.Journal.Repository.CompiledModels
{
    public partial class TradingJournalDataContextModel
    {
        private TradingJournalDataContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("4017e6e1-7e1e-4bef-aa5f-2b7475e7df64"), entityTypeCount: 6)
        {
        }

        partial void Initialize()
        {
            var dataElement = DataElementEntityType.Create(this);
            var contentRecord = ContentRecordEntityType.Create(this);
            var contentRecord0 = ContentRecord0EntityType.Create(this);
            var journalData = JournalDataEntityType.Create(this);
            var tradeComposite = TradeCompositeEntityType.Create(this);
            var tradeElement = TradeElementEntityType.Create(this);

            DataElementEntityType.CreateForeignKey1(dataElement, tradeComposite);
            DataElementEntityType.CreateForeignKey2(dataElement, tradeElement);
            ContentRecordEntityType.CreateForeignKey1(contentRecord, dataElement);
            ContentRecord0EntityType.CreateForeignKey1(contentRecord0, dataElement);
            TradeCompositeEntityType.CreateForeignKey1(tradeComposite, tradeElement);
            TradeElementEntityType.CreateForeignKey1(tradeElement, tradeComposite);

            DataElementEntityType.CreateAnnotations(dataElement);
            ContentRecordEntityType.CreateAnnotations(contentRecord);
            ContentRecord0EntityType.CreateAnnotations(contentRecord0);
            JournalDataEntityType.CreateAnnotations(journalData);
            TradeCompositeEntityType.CreateAnnotations(tradeComposite);
            TradeElementEntityType.CreateAnnotations(tradeElement);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.0");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
