// <auto-generated />
using JTA.Infrastructure.JTA.Journal.Repository.CompiledModels;
using JTA.Journal.Repository;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(TradingJournalDataContext), typeof(TradingJournalDataContextModel))]
