name: "Common .NET Build Steps"
description: "Restore, build, and optionally test a .NET project"

inputs:
  project-path:
    description: "Path to the .csproj file to build"
    required: true
  run-tests:
    description: "Run tests if true"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "9.0.x"

    - name: Restore
      shell: bash
      run: dotnet restore ${{ inputs.project-path }}

    - name: Build
      shell: bash
      run: dotnet build --no-restore ${{ inputs.project-path }}

    - name: Test
      if: ${{ inputs.run-tests == 'true' }}
      shell: bash
      run: dotnet test --no-build --verbosity normal ${{ inputs.project-path }}
