name: Build & Publish .NET Projects

on:
  push:
    tags:
      - 'v*'               # Trigger on any tag starting with 'v'
    paths:
      - "AssetsFlow.Server/**"
      - ".1/PriceAlerts.Server/**"
  workflow_dispatch:

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - solution-path: ./AssetsFlow.Server
            project-filepath: ./AssetsFlow.Server/AssetsFlow.Web.API/AssetsFlowWeb.API.csproj
            build-docker: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Git tags
        run: git fetch --tags --force

      - name: .NET Build Composite
        uses: ./.github/actions/common-build-steps-dotnet
        with:
          solution-path: ${{ matrix.solution-path }}

      - name: Publish
        run: dotnet publish -c Release -r linux-x64 -o ./publish ${{ matrix.project-filepath }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set combined version (tag + timestamp)
        id: set_version
        run: |
          TIMESTAMP=$(TZ="Asia/Jerusalem" date +%Y-%m-%d_%H-%M)
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            TAG_VERSION="${GITHUB_REF#refs/tags/}"
            VERSION="${TAG_VERSION}-${TIMESTAMP}"
          else
            VERSION="v${TIMESTAMP}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version set to $VERSION"

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.solution-path }}/app/Dockerfile
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT_SHA=${{ github.sha }}
          tags: |
            ghcr.io/shaunday/horizons-retrospective/assetsflow-backend:${{ env.VERSION }}
            ghcr.io/shaunday/horizons-retrospective/assetsflow-backend:latest
