name: Build & Test .NET Projects

on:
  push:
    branches:
      - main
    paths:
      - "./AssetsFlow.Server/**"
      - "./PriceAlerts.Server/**"
  workflow_dispatch:

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution-path:
          - ./AssetsFlow.Server
          - ./PriceAlerts.Server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: .NET Build Composite
        uses: ./.github/actions/common-build-steps-dotnet
        with:
          solution-path: ${{ matrix.solution-path }}
