name: Build & Test .NET Projects

on:
  push:
    branches:
      - main
    paths:
      - "./Server.AssetsFlow/**"
      - "./Server.PriceAlerts/**"
  workflow_dispatch:

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution-path:
          - ./Server.AssetsFlow/AssetsFlow.Server.sln
          - ./Server.PriceAlerts/PriceAlerts.Server.sln

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: .NET Build Composite
        uses: ./.github/actions/.NET-Common-Build-Steps
        with:
          solution-path: ${{ matrix.solution-path }}
