name: Build & Test .NET Projects

on:
  push:
    branches:
      - main
    paths:
      - "./Server.AssetsFlow/**"
      - "./Server.PriceAlerts/**"
  workflow_dispatch:

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution-path:
          - ./Server.AssetsFlow
          - ./Server.PriceAlerts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: .NET Build Composite
        uses: ./.github/actions/123
        with:
          solution-path: ${{ matrix.solution-path }}
