name: Build & Publish .NET Projects

on:
  push:
    branches:
      - main
    paths:
      - "./AssetsFlow.Server/**"
      - "./PriceAlerts.Server/**"
  workflow_dispatch:

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution-path:
          - ./AssetsFlow.Server
          - ./PriceAlerts.Server
        project-filepath:
         - ./AssetsFlow.Server/AssetsFlow.Web.API/AssetsFlowWeb.API.csproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: .NET Build Composite
        uses: ./.github/actions/common-build-steps-dotnet
        with:
          solution-path: ${{ matrix.solution-path }}
          
      - name: Publish
        run: dotnet publish -c Release -r linux-x64 -o ./publish ${{ matrix.project-filepath }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get project name
        id: project-name
        run: |
           name=$(basename "${{ matrix.project-filepath }}" .csproj | tr '[:upper:]' '[:lower:]')
           echo "name=$name" >> $GITHUB_OUTPUT


      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{matrix.solution-path}}/Dockerfile
          push: true
          tags: ghcr.io/shaunday/horizons-retrospective/${{ steps.project-name.outputs.name }}:latest
