name: Build & Publish .NET Projects

on:
  push:
    branches:
      - main
    paths:
      - "./Server.AssetsFlow/**"
      - "./Server.PriceAlerts/**"
  workflow_dispatch:

jobs:
  Publish-AssetsFlow:
    needs: Test-AssetsFlow
    uses: ./.github/workflows/.NET Build CommonSteps.yml
    with:
      server-path: ./Server.AssetsFlow

    steps:
    - name: Publish
      run: dotnet publish -c Release -r linux-x64 -o ./publish ${{ inputs.server-path }}
