name: AF Server - Build & Publish on Version Tag

on:
  push:
    tags:
      - 'v*'
    paths:
      - "AssetsFlow.Server/**"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Run Dotnet Build & Publish Action
        uses: ./.github/actions/dotnet-build-publish
        with:
          project-path: ./AssetsFlow.Server/AssetsFlow.Web.API
          image-name: assetsflow-backend
          github-token: ${{ secrets.GITHUB_TOKEN }}
