name: UserService - Build & Publish on Version Tag

on:
  push:
    tags:
      - 'v*'
    paths:
      - "Common.Net/HsR.UserService.All/**"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Run Dotnet Build & Publish Action
        uses: ./.github/actions/dotnet-build-publish
        with:
          project-path: ./Common.Net/HsR.UserService.All/HsR.UserService.Host
          image-name: userservice-backend
          github-token: ${{ secrets.GITHUB_TOKEN }}
