name: Backup Supabase Database

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3:00 AM UTC
  workflow_dispatch:     # Allow manual runs too

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Dump Supabase Database
        run: |
          pg_dump "$SUPABASE_DB_URL" | gzip > backup-$(date +%F).sql.gz
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

      - name: Upload Backup as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup-$(date +%F)
          path: backup-*.sql.gz
