name: Build & Test .NET Server

on:
  push:
    branches:
      - main
    paths:
      - "./Server/**"
  workflow_dispatch:  # Allow manual triggers

jobs:
  pre-build:
    uses: ./.github/workflows/reusable-dotnet-job.yaml
    with:
      job_name: Pre-Build
      dotnet_command: restore

  build:
    uses: ./.github/workflows/reusable-dotnet-job.yaml
    needs: pre-build  # Run after pre-build
    with:
      job_name: Build
      dotnet_command: build --no-restore
