name: Build & Test .NET Server

on:
  push:
    branches:
      - main
    paths:
      - "./Server/**"
  workflow_dispatch:  # Allow manual triggers  

env:
  SERVER_PATH: ./Server  # Define the server path globally

jobs:
  restore:
    runs-on: ubuntu-latest 
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0  # Docker container with .NET SDK 9

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore .NET dependencies
        run: dotnet restore
        working-directory: ${{ env.SERVER_PATH }}

      - name: Upload restored dependencies
        uses: actions/upload-artifact@v3
        with:
          name: restore-artifacts
          path: ${{ env.SERVER_PATH }}/obj

  build:
    needs: restore  
    runs-on: ubuntu-latest 
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download restored dependencies
        uses: actions/download-artifact@v3
        with:
          name: restore-artifacts
          path: ${{ env.SERVER_PATH }}/obj

      - name: Build .NET project
        run: dotnet build --no-restore
        working-directory: ${{ env.SERVER_PATH }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: public/

  test:
    needs: build 
    runs-on: ubuntu-latest 
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0  
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: public

      #- name: Run .NET tests
     #   run: dotnet test --no-build --verbosity normal
     #   working-directory: ${{ env.SERVER_PATH }}
