name: Docker Login

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  login:
    runs-on: ubuntu-latest  # The host runner

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
