name: Build & Test Javascript projects

on:
  push:
    paths:
      - "AssetsFlow.Client.React/**"
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-path:
          - "AssetsFlow.Client.React"

    steps:
      - uses: actions/checkout@v4

      - name: Build & Test using reusable action
        uses: ./.github/workflows/jsts-build-common.yml
        with:
          project-path: ${{ matrix.project-path }}