name: Build & Test Javascript projects

on:
  push:
    paths:
      - "AssetsFlow.Service.ChatWiz/**"
      - "AssetsFlow.Client.React/**"
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect changed project paths from predefined list
        id: set-matrix
        run: |
          KNOWN_PATHS=(
            "AssetsFlow.Service.ChatWiz"
            "AssetsFlow.Client.React"
          )

          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)

          MATRIX_LIST=()
          for path in "${KNOWN_PATHS[@]}"; do
            if echo "$CHANGED_FILES" | grep -q "^$path/"; then
              MATRIX_LIST+=("\"./$path\"")
            fi
          done

          # Create JSON array
          MATRIX_JSON="[$(IFS=,; echo "${MATRIX_LIST[*]}")]"
          echo "matrix=$MATRIX_JSON" >> "$GITHUB_OUTPUT"
          echo "Matrix paths: $MATRIX_JSON"
        shell: bash

  build:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-path: ${{ fromJson(needs.detect-changes.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17'

      - name: Install dependencies
        run: cd ${{ matrix.project-path }} && npm install

      - name: Run build
        run: cd ${{ matrix.project-path }} && npm run build
