      - name: Detect changed project paths from predefined list
        id: set-matrix
        run: |
          KNOWN_PATHS=(
            "AssetsFlow.Server.ChatWiz"
            "AssetsFlow.Client.React"
          )

          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

          # Try to get upstream branch
          UPSTREAM=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null || true)

          # If no upstream or invalid, fall back
          if [ -n "$UPSTREAM" ] && git show-ref --verify --quiet "refs/remotes/${UPSTREAM}"; then
            BASE_BRANCH="$UPSTREAM"
          else
            BASE_BRANCH="origin/main"
          fi

          echo "Current branch: $CURRENT_BRANCH"
          echo "Using base branch: $BASE_BRANCH"

          git fetch origin $BASE_BRANCH

          CHANGED_FILES=$(git diff --name-only $BASE_BRANCH...HEAD)

          echo "Changed files:"
          echo "$CHANGED_FILES"

          MATRIX_LIST=()
          for path in "${KNOWN_PATHS[@]}"; do
            if echo "$CHANGED_FILES" | grep -q "^$path/"; then
              MATRIX_LIST+=("\"./$path\"")
            fi
          done

          MATRIX_JSON="[$(IFS=,; echo "${MATRIX_LIST[*]}")]"
          echo "matrix=$MATRIX_JSON" >> "$GITHUB_OUTPUT"
          echo "Matrix paths: $MATRIX_JSON"
        shell: bash
