name: Build & Test Javascript projects

on:
  push:
    paths:
      - "AssetsFlow.Server.ChatWiz/**"
      - "AssetsFlow.Client.React/**"
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # fetch full history to see all files

      - name: Detect changed project paths from predefined list
        id: set-matrix
        run: |
          KNOWN_PATHS=(
            "AssetsFlow.Server.ChatWiz"
            "AssetsFlow.Client.React"
          )

          # Current branch
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $CURRENT_BRANCH"

          # List all files in this branch
          CHANGED_FILES=$(git ls-tree -r --name-only HEAD)
          echo "Files in branch:"
          echo "$CHANGED_FILES"

          # Build matrix for changed paths
          MATRIX_LIST=()
          for path in "${KNOWN_PATHS[@]}"; do
            if echo "$CHANGED_FILES" | grep -q "^$path/"; then
              MATRIX_LIST+=("\"./$path\"")
            fi
          done

          MATRIX_JSON="[$(IFS=,; echo "${MATRIX_LIST[*]}")]"
          echo "matrix=$MATRIX_JSON" >> "$GITHUB_OUTPUT"
          echo "Matrix paths: $MATRIX_JSON"
        shell: bash

  build:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-path: ${{ fromJson(needs.detect-changes.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17'

      - name: Install dependencies
        run: cd ${{ matrix.project-path }} && npm install

      - name: Run build
        run: cd ${{ matrix.project-path }} && npm run build

      - name: Run audit
        run: cd ${{ matrix.project-path }} && npm run audit

      # Uncomment below to add lint and test steps
      # - name: Run lint
      #   run: cd ${{ matrix.project-path }} && npm run lint
      #
      # - name: Run tests
      #   run: cd ${{ matrix.project-path }} && npm test
