name: Supabase Database Backup

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3:00 AM UTC
  workflow_dispatch:     # Manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Set backup filename
        id: vars
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Dump Supabase Database
        run: |
          pg_dump "$SUPABASE_DB_URL" | gzip > backup-${{ steps.vars.outputs.date }}.sql.gz
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

      - name: Upload Backup as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup-${{ steps.vars.outputs.date }}
          path: backup-${{ steps.vars.outputs.date }}.sql.gz
